"""
validate_audio_features.py — Spotify audio features endpoint validation script

Tests whether the Spotify audio features endpoint is accessible using real
credentials and a track ID from the user's library export.

Writes a flag file at pipeline/.audio_features_available that Phase 2 reads
to determine whether to fetch audio features or skip that enrichment step.

Usage:
    cd pipeline
    python validate_audio_features.py
    python validate_audio_features.py --export-path ~/Downloads/"Spotify Account Data"/YourLibrary.json
"""

import argparse
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

# Load .env from project root before importing anything that reads env vars
_PROJECT_ROOT = Path(__file__).parent.parent.resolve()
_DOTENV_PATH = _PROJECT_ROOT / ".env"

try:
    from dotenv import load_dotenv
    load_dotenv(_DOTENV_PATH)
except ImportError:
    print("WARNING: python-dotenv not installed. Reading credentials from environment only.")

try:
    import spotipy
    from spotipy.oauth2 import SpotifyClientCredentials
except ImportError:
    print("ERROR: spotipy is not installed. Run: pip install spotipy")
    sys.exit(1)

# Import parse_library from the same directory
sys.path.insert(0, str(Path(__file__).parent))
from parse_library import parse_liked_tracks

# Path to write the flag file
_FLAG_FILE = Path(__file__).parent / ".audio_features_available"
_DEFAULT_EXPORT_PATH = Path("~/Downloads/Spotify Account Data/YourLibrary.json").expanduser()


def _write_flag(available: bool, track_id: str) -> None:
    """Write the AUDIO_FEATURES_AVAILABLE flag file."""
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    value = "true" if available else "false"
    content = (
        "# Auto-generated by validate_audio_features.py\n"
        "# Do not edit manually\n"
        f"AUDIO_FEATURES_AVAILABLE={value}\n"
        f"VALIDATED_AT={timestamp}\n"
        f"VALIDATED_TRACK_ID={track_id}\n"
    )
    _FLAG_FILE.write_text(content, encoding="utf-8")
    print(f"\nFlag file written: {_FLAG_FILE}")


def _phase2_guidance(available: bool) -> None:
    """Print human-readable guidance for Phase 2 based on the result."""
    print()
    print("=" * 60)
    print("Phase 2 Guidance")
    print("=" * 60)
    if available:
        print("  Audio features are AVAILABLE.")
        print("  Phase 2 enrichment should:")
        print("    - Call sp.audio_features() in batches of up to 100 tracks")
        print("    - Store: danceability, energy, valence, tempo, key, mode, etc.")
        print("    - These enable audio-feature-based filtering in Phase 4")
    else:
        print("  Audio features are NOT AVAILABLE (403 or error).")
        print("  Phase 2 enrichment should:")
        print("    - Skip audio features entirely")
        print("    - Keep audio feature columns nullable in DB schema")
        print("    - Phase 4 UI should hide audio feature charts gracefully")
        print("    - Consider using a Spotify account with Extended Quota Mode")
        print("      or an older app registration that predates Nov 2024 restrictions")
    print("=" * 60)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Validate Spotify audio features endpoint accessibility."
    )
    parser.add_argument(
        "--export-path",
        type=str,
        default=None,
        help="Path to YourLibrary.json (overrides SPOTIFY_EXPORT_PATH env var and default path)",
    )
    args = parser.parse_args()

    # --- 1. Check credentials ---
    client_id = os.environ.get("SPOTIFY_CLIENT_ID", "").strip()
    client_secret = os.environ.get("SPOTIFY_CLIENT_SECRET", "").strip()

    placeholder_values = {"your_spotify_client_id", "your_spotify_client_secret", ""}
    if client_id in placeholder_values or client_secret in placeholder_values:
        print("ERROR: Spotify credentials are missing or still set to placeholder values.")
        print()
        print("Set them in your project root .env file:")
        print("  SPOTIFY_CLIENT_ID=<your client id>")
        print("  SPOTIFY_CLIENT_SECRET=<your client secret>")
        print()
        print("Get credentials at: https://developer.spotify.com/dashboard")
        print("  1. Log in -> Create App")
        print("  2. Copy Client ID and Client Secret")
        sys.exit(1)

    print(f"Credentials loaded from: {_DOTENV_PATH}")
    print(f"  Client ID: {client_id[:8]}{'*' * (len(client_id) - 8)}")

    # --- 2. Get a real track ID from the user's library ---
    export_path_str = (
        args.export_path
        or os.environ.get("SPOTIFY_EXPORT_PATH")
        or str(_DEFAULT_EXPORT_PATH)
    )
    export_path = Path(export_path_str).expanduser().resolve()

    print(f"\nLoading track from library export: {export_path}")
    try:
        tracks = parse_liked_tracks(export_path)
    except FileNotFoundError as e:
        print(f"ERROR: {e}")
        print("Provide --export-path or set SPOTIFY_EXPORT_PATH.")
        sys.exit(1)
    except ValueError as e:
        print(f"ERROR parsing library: {e}")
        sys.exit(1)

    if not tracks:
        print("ERROR: No tracks found in library export. Cannot proceed.")
        sys.exit(1)

    test_track = tracks[0]
    track_id = test_track["spotify_id"]
    print(f"  Testing with track: '{test_track['name']}' by {test_track['artist_name']}")
    print(f"  Track ID: {track_id}")

    # --- 3. Create Spotipy client ---
    print("\nAuthenticating with Spotify (Client Credentials flow)...")
    try:
        auth_manager = SpotifyClientCredentials(
            client_id=client_id,
            client_secret=client_secret,
        )
        sp = spotipy.Spotify(auth_manager=auth_manager)
        # Trigger token fetch to catch auth errors early
        _ = auth_manager.get_access_token(as_dict=False)
        print("  Authentication: OK")
    except Exception as e:
        err_str = str(e)
        if "401" in err_str or "invalid_client" in err_str.lower() or "unauthorized" in err_str.lower():
            print(f"ERROR: Authentication failed — invalid client credentials.")
            print(f"  Details: {e}")
            print("  Check that SPOTIFY_CLIENT_ID and SPOTIFY_CLIENT_SECRET are correct.")
        else:
            print(f"ERROR: Failed to authenticate with Spotify: {e}")
        sys.exit(1)

    # --- 4. Call audio features endpoint ---
    print(f"\nCalling audio_features endpoint for track {track_id}...")
    available = False

    try:
        result = sp.audio_features([track_id])

        if result and result[0] is not None:
            features = result[0]
            available = True
            print("\nAudio features endpoint is AVAILABLE.")
            print(f"  Sample data for '{test_track['name']}':")
            feature_keys = [
                "danceability", "energy", "valence", "tempo",
                "key", "mode", "loudness", "speechiness",
            ]
            for key in feature_keys:
                if key in features:
                    print(f"    {key}: {features[key]}")
        else:
            print("\nAudio features endpoint returned empty result (no features data).")
            print("This may indicate the endpoint is restricted for your app.")
            available = False

    except spotipy.exceptions.SpotifyException as e:
        if e.http_status == 403:
            print(f"\nAudio features endpoint returned 403 Forbidden.")
            print("This is EXPECTED for Spotify apps registered after November 2024.")
            print("The audio features endpoint was restricted to existing apps.")
            available = False
        elif e.http_status == 401:
            print(f"\nERROR: 401 Unauthorized — token may have expired or credentials are invalid.")
            print(f"  Details: {e}")
            sys.exit(1)
        else:
            print(f"\nSpotify API error (HTTP {e.http_status}): {e}")
            print("Writing flag as false due to unexpected error.")
            available = False
    except Exception as e:
        print(f"\nUnexpected error calling Spotify API: {e}")
        print("Writing flag as false.")
        available = False

    # --- 5. Write flag file and print guidance ---
    _write_flag(available, track_id)
    _phase2_guidance(available)


if __name__ == "__main__":
    main()
